repos:
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
      language_version: python3.10

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
      language_version: python3.10

-   repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
    - id: xenon
      args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        exclude: ^tests/
        args:
          - -s
          - B101
