[tool.poetry]
name = "scikit-fingerprints"
version = "1.1.2"
description = "Library for effective molecular fingerprints calculation"
authors = [
    "Scikit-Fingerprints Development Team <scikitfingerprints@gmail.com>",
    "Jakub Adamczyk <jakub.adamczyk10@gmail.com>",
    "Przemyslaw Kukla <przemek.kukla0703@gmail.com>",
    "Piotr Ludynia <piotrztych@gmail.com>",
    "Michal Szafarczyk <adammichal657@gmail.com>",
]
repository = "https://github.com/Arch4ngel21/scikit-fingerprints"
license = "MIT"
packages = [
    { include = "skfp" }
]

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

datasketch = "*"
e3fp = "*"
joblib = "*"
numpy = "^1.20.0"
pandas = "*"
rdkit = "*"
scikit-learn = "*"
scipy = "*"
tqdm = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
isort = "*"
pre-commit = "*"
pyright = "*"
pytest = "*"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.pytest.ini_options]
python_files = "*.py"

[tool.pyright]
include = ["skfp", "tests"]
pythonVersion = "3.9"  # minimal Python version to support

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
