[tool.poetry]
name = "emf" #this NEEDS to be changed to the other name (for example scikit-emf), however
#either poetry or git do not allow to change the name of the project and still work
#needs to be fixed ASAP
version = "1.0.0"
description = "Library for effective chemical fingerprints calculation"
authors = ["Michal Szafarczyk <adammichal657@gmail.com>", "Piotr Ludynia",
    "Przemyslaw Kukla <przemek.kukla0703@gmail.com>"]
repository = "https://github.com/Arch4ngel21/emf"
license = "MIT"

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.0"
pandas = "*"
scipy = "*"
joblib = "*"
rdkit = "*"
scikit-learn = "*"  # No minimal version specified, will use the latest available
torch = {version = "^2.0.1+cpu", source = "pytorch"}
torchvision = {version = "^0.15.2+cpu", source = "pytorch"}

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

