name: Python package workflow

on: [push]

env:
  POETRY_VENV: poetry_venv

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        python3 -m venv $POETRY_VENV
        $POETRY_VENV/bin/pip install -U pip setuptools
        $POETRY_VENV/bin/pip install poetry

    - name: Install dependencies using Poetry
      run: poetry install --with test

    - name: Run light tests with pytest
      run: poetry run pytest tests/fingerprints_tests_light.py

