name: Python package workflow

on: [pull_request]

env:
  POETRY_VENV: poetry_venv
  POETRY: poetry_venv/bin/poetry

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        python3 -m venv $POETRY_VENV
        $POETRY_VENV/bin/pip install -U pip setuptools
        $POETRY_VENV/bin/pip install poetry

    - name: Install dependencies using Poetry
      run: $POETRY install --with test

    - name: Install poetry plugins
      run: $POETRY plugin add poetry-plugin-sort

    - name: Check pre-commit
      run: $POETRY run pre-commit run --all-files

    - name: Run tests with pytest
      run: $POETRY run pytest tests

